// Seed devotees shown in the admin dashboard until the first real booking is
// made. Mirrors the demo profiles that previously lived in localStorage, so
// the dashboard looks the same after the move to server-side storage.
import type { UserProfile } from "./storage";

export const DEMO_USERS: UserProfile[] = [
  {
    id: "USRXKV36Q",
    name: "Aarav Sharma",
    gotra: "Kashyap",
    city: "New Delhi",
    phone: "9876543210",
    email: "",
    createdAt: "2026-08-04T09:59:26.627Z",
    bookings: [
      {
        bookingId: "SK6HNM7L",
        poojaSlug: "satyanarayan-katha",
        poojaTitle: "Satyanarayan Katha",
        date: "Wed, 5 Aug",
        time: "6:00 AM",
        panditName: "Pt. Rama Krishna Sharma",
        amount: 1101,
        discount: 0,
        couponCode: null,
        addonCount: 0,
        createdAt: "2026-08-04T09:59:26.626Z",
        status: "confirmed",
      },
    ],
  },
  {
    id: "USRIA7NAG",
    name: "Rohan Verma",
    gotra: "Kaushik",
    city: "Lucknow",
    phone: "9812345670",
    email: "",
    createdAt: "2026-08-04T11:00:33.947Z",
    bookings: [
      {
        bookingId: "SKHVATCB",
        poojaSlug: "hanuman-pooja",
        poojaTitle: "Hanuman Pooja",
        date: "Wed, 12 Aug",
        time: "7:00 PM IST",
        panditName: "Assigned by The Temple Puja",
        amount: 501,
        discount: 0,
        couponCode: null,
        addonCount: 0,
        createdAt: "2026-08-04T11:00:33.929Z",
        status: "confirmed",
      },
    ],
  },
  {
    id: "USRY5W6J0",
    name: "Meera Joshi",
    gotra: "Shandilya",
    city: "Varanasi",
    phone: "9123456789",
    email: "",
    createdAt: "2026-08-04T11:23:39.949Z",
    bookings: [
      {
        bookingId: "SKVRRPLC",
        poojaSlug: "satyanarayan-katha",
        poojaTitle: "Satyanarayan Katha",
        date: "Thu, 20 Aug",
        time: "—",
        panditName: "Assigned by The Temple Puja",
        reason: "For my son's wedding and family peace",
        amount: 1101,
        discount: 0,
        couponCode: null,
        addonCount: 0,
        createdAt: "2026-08-04T11:23:39.936Z",
        status: "cancelled",
        cancelledAt: "2026-08-04T12:12:38.789Z",
      },
    ],
  },
  {
    id: "USRUPF80B",
    name: "Coupon Test User",
    gotra: "Bhardwaj",
    city: "Mumbai",
    phone: "9999999991",
    email: "",
    createdAt: "2026-08-07T05:51:37.434Z",
    bookings: [
      {
        bookingId: "SKLDBZP8",
        poojaSlug: "hanuman-pooja",
        poojaTitle: "Hanuman Pooja",
        date: "Fri, 7 Aug",
        time: "—",
        panditName: "Assigned by The Temple Puja",
        reason: "Testing the coupon system for the demo booking",
        amount: 351,
        discount: 150,
        couponCode: "TEMPLE30",
        addonCount: 0,
        createdAt: "2026-08-07T05:51:37.433Z",
        status: "confirmed",
      },
    ],
  },
];
